### PR TITLE
Add binance testnet-mainnet config in truffle-config

### PR DESCRIPTION
**Pull request by aadorian**
Add Binance TestNet and Mainnet  resolving comments https://github.com/smartcontractkit/box/pull/30

### CODE REVIEW

**Review by PatrickAlphaC — CHANGES_REQUESTED** [review]
Thanks for this PR! Could you change the name of the bsc testnet to a more appropriate name?

**Review by PatrickAlphaC — APPROVED** [review]

**Review by PatrickAlphaC — APPROVED** [review]

**Comment by PatrickAlphaC** [comment]
Thanks for this! I made a few tweaks, but all in all, thank you! For the box, we hold off on the mainnet implementations for now.

**Comment by aadorian** [comment]
> Thanks for this! I made a few tweaks, but all in all, thank you! For the box, we hold off on the mainnet implementations for now.

Many thanks to you @PatrickAlphaC  A pleasure to collaborate with the project :) Congratulations to the Chainlink Hackathon Team, I really enjoyed your presentations, really excellent !!

**Comment by PatrickAlphaC** [comment]
🙏🙏🙏

Glad to hear it!!

**Pull request merged**
